package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;
import java.util.ArrayList;

public class Indexs  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indexs.id
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indexs.label
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indexs.report_type
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    private String reportType;
    
    private ArrayList<Indexs> children ;

    public ArrayList<Indexs> getChilds() {
    	if(children==null)
    		children=new ArrayList<Indexs>();
    	
    	return children;
    }

	public void setChilds(ArrayList<Indexs> childs) {
    	this.children = childs;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indexs.id
     *
     * @return the value of indexs.id
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indexs.id
     *
     * @param id the value for indexs.id
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indexs.label
     *
     * @return the value of indexs.label
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    public String getLabel() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indexs.label
     *
     * @param label the value for indexs.label
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    public void setLabel(String label) {
        this.text = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indexs.report_type
     *
     * @return the value of indexs.report_type
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indexs.report_type
     *
     * @param reportType the value for indexs.report_type
     *
     * @mbggenerated Thu Aug 28 10:46:30 CST 2014
     */
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }
}