package com.myhexin.DB.mybatis.mode;

public class IndexInteraction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_interaction.id
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_interaction.key
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_interaction.interaction
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    private String interaction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_interaction.id
     *
     * @return the value of index_interaction.id
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_interaction.id
     *
     * @param id the value for index_interaction.id
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_interaction.key
     *
     * @return the value of index_interaction.key
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_interaction.key
     *
     * @param key the value for index_interaction.key
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_interaction.interaction
     *
     * @return the value of index_interaction.interaction
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    public String getInteraction() {
        return interaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_interaction.interaction
     *
     * @param interaction the value for index_interaction.interaction
     *
     * @mbggenerated Thu Nov 06 10:49:17 CST 2014
     */
    public void setInteraction(String interaction) {
        this.interaction = interaction;
    }
}