package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class IndexFieldV  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_field_v.index_id
     *
     * @mbggenerated Fri Nov 07 13:49:33 CST 2014
     */
    private Integer indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_field_v.fileds
     *
     * @mbggenerated Fri Nov 07 13:49:33 CST 2014
     */
    private String fileds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_field_v.index_id
     *
     * @return the value of index_field_v.index_id
     *
     * @mbggenerated Fri Nov 07 13:49:33 CST 2014
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_field_v.index_id
     *
     * @param indexId the value for index_field_v.index_id
     *
     * @mbggenerated Fri Nov 07 13:49:33 CST 2014
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_field_v.fileds
     *
     * @return the value of index_field_v.fileds
     *
     * @mbggenerated Fri Nov 07 13:49:33 CST 2014
     */
    public String getFileds() {
        return fileds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_field_v.fileds
     *
     * @param fileds the value for index_field_v.fileds
     *
     * @mbggenerated Fri Nov 07 13:49:33 CST 2014
     */
    public void setFileds(String fileds) {
        this.fileds = fileds;
    }
}