package com.myhexin.DB.mybatis.mode;

public class NoParserWell {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column no_parser_well.id
     *
     * @mbggenerated Mon Oct 27 14:33:22 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column no_parser_well.no_parser_well
     *
     * @mbggenerated Mon Oct 27 14:33:22 CST 2014
     */
    private String noParserWell;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column no_parser_well.id
     *
     * @return the value of no_parser_well.id
     *
     * @mbggenerated Mon Oct 27 14:33:22 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column no_parser_well.id
     *
     * @param id the value for no_parser_well.id
     *
     * @mbggenerated Mon Oct 27 14:33:22 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column no_parser_well.no_parser_well
     *
     * @return the value of no_parser_well.no_parser_well
     *
     * @mbggenerated Mon Oct 27 14:33:22 CST 2014
     */
    public String getNoParserWell() {
        return noParserWell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column no_parser_well.no_parser_well
     *
     * @param noParserWell the value for no_parser_well.no_parser_well
     *
     * @mbggenerated Mon Oct 27 14:33:22 CST 2014
     */
    public void setNoParserWell(String noParserWell) {
        this.noParserWell = noParserWell;
    }
}