package com.myhexin.DB.mybatis.mode;

public class NoParser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column no_parser.id
     *
     * @mbggenerated Mon Oct 27 14:31:51 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column no_parser.no_parser
     *
     * @mbggenerated Mon Oct 27 14:31:51 CST 2014
     */
    private String noParser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column no_parser.id
     *
     * @return the value of no_parser.id
     *
     * @mbggenerated Mon Oct 27 14:31:51 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column no_parser.id
     *
     * @param id the value for no_parser.id
     *
     * @mbggenerated Mon Oct 27 14:31:51 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column no_parser.no_parser
     *
     * @return the value of no_parser.no_parser
     *
     * @mbggenerated Mon Oct 27 14:31:51 CST 2014
     */
    public String getNoParser() {
        return noParser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column no_parser.no_parser
     *
     * @param noParser the value for no_parser.no_parser
     *
     * @mbggenerated Mon Oct 27 14:31:51 CST 2014
     */
    public void setNoParser(String noParser) {
        this.noParser = noParser;
    }
}