package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class NormalRelation  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_relation.prop_id
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    private Integer propId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_relation.type
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_relation.unit
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_relation.prop_id
     *
     * @return the value of normal_relation.prop_id
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    public Integer getPropId() {
        return propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_relation.prop_id
     *
     * @param propId the value for normal_relation.prop_id
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    public void setPropId(Integer propId) {
        this.propId = propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_relation.type
     *
     * @return the value of normal_relation.type
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_relation.type
     *
     * @param type the value for normal_relation.type
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_relation.unit
     *
     * @return the value of normal_relation.unit
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_relation.unit
     *
     * @param unit the value for normal_relation.unit
     *
     * @mbggenerated Thu Nov 06 14:59:24 CST 2014
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }
}