package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class ObjectRelationV  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column object_relation_v.prop_id
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    private Integer propId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column object_relation_v.index_id
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    private Integer indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column object_relation_v.label
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column object_relation_v.report_type
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    private String reportType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column object_relation_v.prop_id
     *
     * @return the value of object_relation_v.prop_id
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    public Integer getPropId() {
        return propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column object_relation_v.prop_id
     *
     * @param propId the value for object_relation_v.prop_id
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    public void setPropId(Integer propId) {
        this.propId = propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column object_relation_v.index_id
     *
     * @return the value of object_relation_v.index_id
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column object_relation_v.index_id
     *
     * @param indexId the value for object_relation_v.index_id
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column object_relation_v.label
     *
     * @return the value of object_relation_v.label
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column object_relation_v.label
     *
     * @param label the value for object_relation_v.label
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column object_relation_v.report_type
     *
     * @return the value of object_relation_v.report_type
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column object_relation_v.report_type
     *
     * @param reportType the value for object_relation_v.report_type
     *
     * @mbggenerated Thu Nov 06 15:01:38 CST 2014
     */
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }
}