package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class ResolveAliasesConflicts  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resolve_aliases_conflicts.aliase_id
     *
     * @mbggenerated Wed Sep 03 14:16:13 CST 2014
     */
    private Integer aliaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resolve_aliases_conflicts.word
     *
     * @mbggenerated Wed Sep 03 14:16:13 CST 2014
     */
    private String word;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resolve_aliases_conflicts.aliase_id
     *
     * @return the value of resolve_aliases_conflicts.aliase_id
     *
     * @mbggenerated Wed Sep 03 14:16:13 CST 2014
     */
    public Integer getAliaseId() {
        return aliaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resolve_aliases_conflicts.aliase_id
     *
     * @param aliaseId the value for resolve_aliases_conflicts.aliase_id
     *
     * @mbggenerated Wed Sep 03 14:16:13 CST 2014
     */
    public void setAliaseId(Integer aliaseId) {
        this.aliaseId = aliaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resolve_aliases_conflicts.word
     *
     * @return the value of resolve_aliases_conflicts.word
     *
     * @mbggenerated Wed Sep 03 14:16:13 CST 2014
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resolve_aliases_conflicts.word
     *
     * @param word the value for resolve_aliases_conflicts.word
     *
     * @mbggenerated Wed Sep 03 14:16:13 CST 2014
     */
    public void setWord(String word) {
        this.word = word;
    }
}