package com.myhexin.DB.mybatis.mode;

public class SearchPropConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_prop_config.id
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_prop_config.typeLabel
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private String typeLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_prop_config.weight
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private Integer weight;

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_prop_config.id
     *
     * @return the value of search_prop_config.id
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_prop_config.id
     *
     * @param id the value for search_prop_config.id
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_prop_config.typeLabel
     *
     * @return the value of search_prop_config.typeLabel
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public String getTypeLabel() {
        return typeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_prop_config.typeLabel
     *
     * @param idnum the value for search_prop_config.typeLabel
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setTypeLabel(String typeLabel) {
        this.typeLabel = typeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_prop_config.weight
     *
     * @return the value of search_prop_config.weight
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_prop_config.weight
     *
     * @param udp the value for search_prop_config.weight
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

	@Override
	public String toString() {
		return "SearchPropConfig [id=" + id + ", typeLabel=" + typeLabel + ", weight=" + weight + "]";
	}
    
}