package com.myhexin.DB.mybatis.mode;

import java.sql.Timestamp;

public class SearchIdConfig {
  
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_id_config.id
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_id_config.idNum
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private String idnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_id_config.udp
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private String udp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_id_config.other
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_id_config.replacement
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private String replacement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_id_config.channel
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    private String channel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_id_config.id
     *
     * @return the value of search_id_config.id
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_id_config.id
     *
     * @param id the value for search_id_config.id
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_id_config.idNum
     *
     * @return the value of search_id_config.idNum
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public String getIdnum() {
        return idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_id_config.idNum
     *
     * @param idnum the value for search_id_config.idNum
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setIdnum(String idnum) {
        this.idnum = idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_id_config.udp
     *
     * @return the value of search_id_config.udp
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public String getUdp() {
        return udp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_id_config.udp
     *
     * @param udp the value for search_id_config.udp
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setUdp(String udp) {
        this.udp = udp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_id_config.other
     *
     * @return the value of search_id_config.other
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_id_config.other
     *
     * @param other the value for search_id_config.other
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setOther(String other) {
        this.other = other;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_id_config.replacement
     *
     * @return the value of search_id_config.replacement
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public String getReplacement() {
        return replacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_id_config.replacement
     *
     * @param other the value for search_id_config.replacement
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setReplacement(String replacement) {
        this.replacement = replacement;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_id_config.channel
     *
     * @return the value of search_id_config.channel
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_id_config.channel
     *
     * @param channel the value for search_id_config.channel
     *
     * @mbggenerated Fri Apr 10 09:34:39 CST 2015
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

	@Override
	public String toString() {
		return "SearchIdPropertyConfig [id=" + id + ", idnum=" + idnum + ", udp=" + udp
				+ ", other=" + other + ", replacement=" + replacement + ", channel=" + channel + "]";
	}
    
}