package com.myhexin.DB.mybatis.mode;

public class StopWords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stop_words.id
     *
     * @mbggenerated Mon Oct 27 14:25:50 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stop_words.stop_words
     *
     * @mbggenerated Mon Oct 27 14:25:50 CST 2014
     */
    private String stopWords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stop_words.id
     *
     * @return the value of stop_words.id
     *
     * @mbggenerated Mon Oct 27 14:25:50 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stop_words.id
     *
     * @param id the value for stop_words.id
     *
     * @mbggenerated Mon Oct 27 14:25:50 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stop_words.stop_words
     *
     * @return the value of stop_words.stop_words
     *
     * @mbggenerated Mon Oct 27 14:25:50 CST 2014
     */
    public String getStopWords() {
        return stopWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stop_words.stop_words
     *
     * @param stopWords the value for stop_words.stop_words
     *
     * @mbggenerated Mon Oct 27 14:25:50 CST 2014
     */
    public void setStopWords(String stopWords) {
        this.stopWords = stopWords;
    }
}