package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class TraditionalSimplifiedMap  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traditional_simplified_map.id
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traditional_simplified_map.traditional
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    private String traditional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traditional_simplified_map.simplified
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    private String simplified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traditional_simplified_map.id
     *
     * @return the value of traditional_simplified_map.id
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traditional_simplified_map.id
     *
     * @param id the value for traditional_simplified_map.id
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traditional_simplified_map.traditional
     *
     * @return the value of traditional_simplified_map.traditional
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    public String getTraditional() {
        return traditional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traditional_simplified_map.traditional
     *
     * @param traditional the value for traditional_simplified_map.traditional
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    public void setTraditional(String traditional) {
        this.traditional = traditional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traditional_simplified_map.simplified
     *
     * @return the value of traditional_simplified_map.simplified
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    public String getSimplified() {
        return simplified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traditional_simplified_map.simplified
     *
     * @param simplified the value for traditional_simplified_map.simplified
     *
     * @mbggenerated Mon Oct 27 10:12:52 CST 2014
     */
    public void setSimplified(String simplified) {
        this.simplified = simplified;
    }
}