{
	"type": <#if type??><#if (type?length>0) >"${type}"<#else>""</#if><#else>""</#if>,
	"sub_type": <#if sub_type??><#if (sub_type?length>0) >"${sub_type}"<#else>""</#if><#else>""</#if>,
	"channel":<#if channel??><#if (channel?length>0) >"${channel}"<#else>""</#if><#else>""</#if>,
	"is_comment": <#if is_comment>"TRUE"<#else>"FALSE"</#if>,
	"seg_num":<#if seg_num??><#if (seg_num?length>0) >"${seg_num}"<#else>""</#if><#else>""</#if>,
	"seg_status": <#if seg_status??><#if (seg_status?length>0) >"${seg_status}"<#else>"0"</#if><#else>"0"</#if>,
	"cmd": "",
	"cmd_web": "",
	"options": "",
	"query": <#if query??><#if (query?length>0) >"${query}"<#else>""</#if><#else>""</#if>,
	"node_list": <#assign node_list=node_list><#include "/node_list.ftl">,
	"id_list": <#if id_list??><#if (id_list?length>0) >${id_list}<#else>""</#if><#else>""</#if>,
	"id_search": <#if id_search??><#if (id_search?length>0) >"${id_search}"<#else>""</#if><#else>""</#if>,
	"yanbao_search": <#if yanbao_search??><#if (yanbao_search?length>0) >${yanbao_search}<#else>""</#if><#else>""</#if>,
	"news_search": <#if news_search??><#if (news_search?length>0) >${news_search}<#else>""</#if><#else>""</#if>,
	"hotnews_search": <#if hotnews_search??><#if (hotnews_search?length>0) >${hotnews_search}<#else>""</#if><#else>""</#if>,
	"report_search": <#if report_search??><#if (report_search?length>0) >${report_search}<#else>""</#if><#else>""</#if>,
	"pubnote_search": <#if pubnote_search??><#if (pubnote_search?length>0) >${pubnote_search}<#else>""</#if><#else>""</#if>,
	"navigation_search": <#if navigation_search??><#if (navigation_search?length>0) >${navigation_search}<#else>""</#if><#else>""</#if>,
	"usersite_search": <#if usersite_search??><#if (usersite_search?length>0) >${usersite_search}<#else>""</#if><#else>""</#if>,
	"investqa_search": <#if investqa_search??><#if (investqa_search?length>0) >${investqa_search}<#else>""</#if><#else>""</#if>,
    "weibo_search": <#if weibo_search??><#if (weibo_search?length>0) >${weibo_search}<#else>""</#if><#else>""</#if>,
    "blog_search": <#if blog_search??><#if (blog_search?length>0) >${blog_search}<#else>""</#if><#else>""</#if>,
    "guba_search": <#if guba_search??><#if (guba_search?length>0) >${guba_search}<#else>""</#if><#else>""</#if>,
    "forum_search": <#if forum_search??><#if (forum_search?length>0) >${forum_search}<#else>""</#if><#else>""</#if>,
    "product_search": <#if product_search??><#if (product_search?length>0) >${product_search}<#else>""</#if><#else>""</#if>,
    "video_search": <#if video_search??><#if (video_search?length>0) >${video_search}<#else>""</#if><#else>""</#if>,
    "info_search": <#if info_search??><#if (info_search?length>0) >${info_search}<#else>""</#if><#else>""</#if>,
    "stockrecommend_search": <#if stockrecommend_search??><#if (stockrecommend_search?length>0) >${stockrecommend_search}<#else>""</#if><#else>""</#if>
}