package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class Aliases implements Serializable{
	
	private static final long serialVersionUID = 1L;

	public Aliases(){
		isDefault = false;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aliases.id
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aliases.index_id
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    private Integer indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aliases.label
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aliases.is_default
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    private Boolean isDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aliases.id
     *
     * @return the value of aliases.id
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aliases.id
     *
     * @param id the value for aliases.id
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aliases.index_id
     *
     * @return the value of aliases.index_id
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aliases.index_id
     *
     * @param indexId the value for aliases.index_id
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aliases.label
     *
     * @return the value of aliases.label
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aliases.label
     *
     * @param label the value for aliases.label
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aliases.is_default
     *
     * @return the value of aliases.is_default
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aliases.is_default
     *
     * @param isDefault the value for aliases.is_default
     *
     * @mbggenerated Wed Sep 03 14:31:33 CST 2014
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }
}