package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class DataRelationV  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_relation_v.prop_id
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    private Integer propId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_relation_v.data_type_id
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    private Integer dataTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_relation_v.label
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_relation_v.prop_id
     *
     * @return the value of data_relation_v.prop_id
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    public Integer getPropId() {
        return propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_relation_v.prop_id
     *
     * @param propId the value for data_relation_v.prop_id
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    public void setPropId(Integer propId) {
        this.propId = propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_relation_v.data_type_id
     *
     * @return the value of data_relation_v.data_type_id
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    public Integer getDataTypeId() {
        return dataTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_relation_v.data_type_id
     *
     * @param dataTypeId the value for data_relation_v.data_type_id
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    public void setDataTypeId(Integer dataTypeId) {
        this.dataTypeId = dataTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_relation_v.label
     *
     * @return the value of data_relation_v.label
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_relation_v.label
     *
     * @param label the value for data_relation_v.label
     *
     * @mbggenerated Thu Nov 06 15:04:56 CST 2014
     */
    public void setLabel(String label) {
        this.label = label;
    }
}