package com.myhexin.DB.mybatis.mode;

public class DateMerge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parser_datemerge_rule.id
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parser_datemerge_rule.text
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parser_datemerge_rule.need_replace
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    private String needReplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parser_datemerge_rule.whole_text
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    private String wholeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parser_datemerge_rule.replace_rule
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    private String replaceRule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parser_datemerge_rule.id
     *
     * @return the value of parser_datemerge_rule.id
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parser_datemerge_rule.id
     *
     * @param id the value for parser_datemerge_rule.id
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parser_datemerge_rule.text
     *
     * @return the value of parser_datemerge_rule.text
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parser_datemerge_rule.text
     *
     * @param text the value for parser_datemerge_rule.text
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parser_datemerge_rule.need_replace
     *
     * @return the value of parser_datemerge_rule.need_replace
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public String getNeedReplace() {
        return needReplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parser_datemerge_rule.need_replace
     *
     * @param needReplace the value for parser_datemerge_rule.need_replace
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public void setNeedReplace(String needReplace) {
        this.needReplace = needReplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parser_datemerge_rule.whole_text
     *
     * @return the value of parser_datemerge_rule.whole_text
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public String getWholeText() {
        return wholeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parser_datemerge_rule.whole_text
     *
     * @param wholeText the value for parser_datemerge_rule.whole_text
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public void setWholeText(String wholeText) {
        this.wholeText = wholeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parser_datemerge_rule.replace_rule
     *
     * @return the value of parser_datemerge_rule.replace_rule
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public String getReplaceRule() {
        return replaceRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parser_datemerge_rule.replace_rule
     *
     * @param replaceRule the value for parser_datemerge_rule.replace_rule
     *
     * @mbggenerated Tue May 05 13:56:54 CST 2015
     */
    public void setReplaceRule(String replaceRule) {
        this.replaceRule = replaceRule;
    }

	@Override
	public String toString() {
		return "DateMerge [id=" + id + ", text=" + text + ", needReplace="
				+ needReplace + ", wholeText=" + wholeText + ", replaceRule="
				+ replaceRule + "]";
	}
}