package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class IndexPropV2  implements Serializable{
    private static final long serialVersionUID = 1L;

    public String toString() {
    	return id + "," + label + "," + isValueProp;
    }
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_prop_v2.id
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_prop_v2.label
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_prop_v2.type
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_prop_v2.index_id
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    private Integer indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_prop_v2.seq_in_index
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    private Integer seqInIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_prop_v2.is_value_prop
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    private Boolean isValueProp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_prop_v2.id
     *
     * @return the value of index_prop_v2.id
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_prop_v2.id
     *
     * @param id the value for index_prop_v2.id
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_prop_v2.label
     *
     * @return the value of index_prop_v2.label
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_prop_v2.label
     *
     * @param label the value for index_prop_v2.label
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_prop_v2.type
     *
     * @return the value of index_prop_v2.type
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_prop_v2.type
     *
     * @param type the value for index_prop_v2.type
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_prop_v2.index_id
     *
     * @return the value of index_prop_v2.index_id
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_prop_v2.index_id
     *
     * @param indexId the value for index_prop_v2.index_id
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_prop_v2.seq_in_index
     *
     * @return the value of index_prop_v2.seq_in_index
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public Integer getSeqInIndex() {
        return seqInIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_prop_v2.seq_in_index
     *
     * @param seqInIndex the value for index_prop_v2.seq_in_index
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public void setSeqInIndex(Integer seqInIndex) {
        this.seqInIndex = seqInIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_prop_v2.is_value_prop
     *
     * @return the value of index_prop_v2.is_value_prop
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public Boolean getIsValueProp() {
        return isValueProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_prop_v2.is_value_prop
     *
     * @param isValueProp the value for index_prop_v2.is_value_prop
     *
     * @mbggenerated Thu Nov 06 14:58:06 CST 2014
     */
    public void setIsValueProp(Boolean isValueProp) {
        this.isValueProp = isValueProp;
    }
}