package com.myhexin.DB.mybatis.mode;

public class Removenodeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RemoveNodeInfo.id
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RemoveNodeInfo.lable
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    private String lable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RemoveNodeInfo.preProp
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    private String preprop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RemoveNodeInfo.preLable
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    private String prelable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RemoveNodeInfo.postProp
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    private String postprop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RemoveNodeInfo.id
     *
     * @return the value of RemoveNodeInfo.id
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RemoveNodeInfo.id
     *
     * @param id the value for RemoveNodeInfo.id
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RemoveNodeInfo.lable
     *
     * @return the value of RemoveNodeInfo.lable
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public String getLable() {
        return lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RemoveNodeInfo.lable
     *
     * @param lable the value for RemoveNodeInfo.lable
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public void setLable(String lable) {
        this.lable = lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RemoveNodeInfo.preProp
     *
     * @return the value of RemoveNodeInfo.preProp
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public String getPreprop() {
        return preprop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RemoveNodeInfo.preProp
     *
     * @param preprop the value for RemoveNodeInfo.preProp
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public void setPreprop(String preprop) {
        this.preprop = preprop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RemoveNodeInfo.preLable
     *
     * @return the value of RemoveNodeInfo.preLable
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public String getPrelable() {
        return prelable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RemoveNodeInfo.preLable
     *
     * @param prelable the value for RemoveNodeInfo.preLable
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public void setPrelable(String prelable) {
        this.prelable = prelable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RemoveNodeInfo.postProp
     *
     * @return the value of RemoveNodeInfo.postProp
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public String getPostprop() {
        return postprop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RemoveNodeInfo.postProp
     *
     * @param postprop the value for RemoveNodeInfo.postProp
     *
     * @mbggenerated Tue Jul 29 14:16:24 CST 2014
     */
    public void setPostprop(String postprop) {
        this.postprop = postprop;
    }
}