package com.myhexin.DB.mybatis.mode;

import java.sql.Timestamp;

public class SearchIdPropertyConfig {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column search_id_property_config.id
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  private Integer id;
  
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column search_id_property_config.idNum
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  private String idnum;
  
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column search_id_property_config.priority
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  private Integer priority;
  
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column search_id_property_config.optime
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  private Timestamp optime;
 
  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column search_id_property_config.id
   *
   * @return the value of search_id_property_config.id
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  public Integer getId() {
      return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column search_id_property_config.id
   *
   * @param id the value for search_id_property_config.id
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  public void setId(Integer id) {
      this.id = id;
  }
  
  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column search_id_property_config.idNum
   *
   * @return the value of search_id_property_config.idNum
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  public String getIdnum() {
      return idnum;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column search_id_property_config.idNum
   *
   * @param idnum the value for search_id_property_config.idNum
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  public void setIdnum(String idnum) {
      this.idnum = idnum;
  }
  
  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column search_id_property_config.priority
   *
   * @return the value of search_id_property_config.priority
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  public Integer getPriority() {
      return priority;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column search_id_property_config.priority
   *
   * @param other the value for search_id_property_config.priority
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  public void setPriority(Integer priority) {
      this.priority = priority;
  }
  
  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column search_id_property_config.optime
   *
   * @return the value of search_id_property_config.optime
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  public Timestamp getOptime() {
      return optime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column search_id_property_config.optime
   *
   * @param other the value for search_id_property_config.optime
   *
   * @mbggenerated Fri Apr 10 09:34:39 CST 2015
   */
  public void setOptime(Timestamp optime) {
      this.optime = optime;
  }
  
  @Override
  public String toString() {
    return "SearchIdConfig [id=" + id + ", idnum=" + idnum 
        + ", priority=" + priority + ", optime=" + optime + "]";
  }
}
