package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class SuperIndexV  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_index_v.super_id
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    private Integer superId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_index_v.index_id
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    private Integer indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_index_v.label
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_index_v.report_type
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    private String reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_index_v.super_lable
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    private String superLable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_index_v.super_report_type
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    private String superReportType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_index_v.super_id
     *
     * @return the value of super_index_v.super_id
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public Integer getSuperId() {
        return superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_index_v.super_id
     *
     * @param superId the value for super_index_v.super_id
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public void setSuperId(Integer superId) {
        this.superId = superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_index_v.index_id
     *
     * @return the value of super_index_v.index_id
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_index_v.index_id
     *
     * @param indexId the value for super_index_v.index_id
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_index_v.label
     *
     * @return the value of super_index_v.label
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_index_v.label
     *
     * @param label the value for super_index_v.label
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_index_v.report_type
     *
     * @return the value of super_index_v.report_type
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_index_v.report_type
     *
     * @param reportType the value for super_index_v.report_type
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_index_v.super_lable
     *
     * @return the value of super_index_v.super_lable
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public String getSuperLable() {
        return superLable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_index_v.super_lable
     *
     * @param superLable the value for super_index_v.super_lable
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public void setSuperLable(String superLable) {
        this.superLable = superLable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_index_v.super_report_type
     *
     * @return the value of super_index_v.super_report_type
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public String getSuperReportType() {
        return superReportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_index_v.super_report_type
     *
     * @param superReportType the value for super_index_v.super_report_type
     *
     * @mbggenerated Thu Nov 06 14:22:18 CST 2014
     */
    public void setSuperReportType(String superReportType) {
        this.superReportType = superReportType;
    }
}