package com.myhexin.DB.mybatis.mode;

import java.io.Serializable;

public class ToLuaExpression  implements Serializable{
    private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_lua_expression.id
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_lua_expression.syntactic_id
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    private String syntacticId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_lua_expression.semantic_ids
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    private String semanticIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_lua_expression.indexs
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    private String indexs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_lua_expression.lua_expression
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    private String luaExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_lua_expression.query
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    private String query;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_lua_expression.id
     *
     * @return the value of to_lua_expression.id
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_lua_expression.id
     *
     * @param id the value for to_lua_expression.id
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_lua_expression.syntactic_id
     *
     * @return the value of to_lua_expression.syntactic_id
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public String getSyntacticId() {
        return syntacticId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_lua_expression.syntactic_id
     *
     * @param syntacticId the value for to_lua_expression.syntactic_id
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public void setSyntacticId(String syntacticId) {
        this.syntacticId = syntacticId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_lua_expression.semantic_ids
     *
     * @return the value of to_lua_expression.semantic_ids
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public String getSemanticIds() {
        return semanticIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_lua_expression.semantic_ids
     *
     * @param semanticIds the value for to_lua_expression.semantic_ids
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public void setSemanticIds(String semanticIds) {
        this.semanticIds = semanticIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_lua_expression.indexs
     *
     * @return the value of to_lua_expression.indexs
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public String getIndexs() {
        return indexs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_lua_expression.indexs
     *
     * @param indexs the value for to_lua_expression.indexs
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public void setIndexs(String indexs) {
        this.indexs = indexs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_lua_expression.lua_expression
     *
     * @return the value of to_lua_expression.lua_expression
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public String getLuaExpression() {
        return luaExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_lua_expression.lua_expression
     *
     * @param luaExpression the value for to_lua_expression.lua_expression
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public void setLuaExpression(String luaExpression) {
        this.luaExpression = luaExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_lua_expression.query
     *
     * @return the value of to_lua_expression.query
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_lua_expression.query
     *
     * @param query the value for to_lua_expression.query
     *
     * @mbggenerated Tue Sep 30 13:59:34 CST 2014
     */
    public void setQuery(String query) {
        this.query = query;
    }
}